### ISSUE TITLE
Question about the usage of Product's Attribute and AttributeOption

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#56]
Question:
1. What the usage of Product's Attribute and AttributeOption?
1. How to combine these two class to describe product?

Thanks advance!

**Comment by gdlcf88** [comment]
For example, when creating a product, I input these:
![image](https://user-images.githubusercontent.com/30018771/85300078-b3c21c80-b4d8-11ea-80a6-4058fe6f7f76.png)
The expected result is as shown in the image:
![image](https://user-images.githubusercontent.com/30018771/85299890-7198db00-b4d8-11ea-95b6-396cb8f161b6.png)
Of course, this is a screenshot of Amazon, the completion of EShop is still very low.

It accepts only the names of Attributes and AttributeOptions since we want to make the management page as soon as possible and continue to improve it later.

**Comment by RayMMond** [comment]
I got it, Thanks.
